testmake: 
	gcc -o testoutput test/*.c *.c src/memory/*.c src/registers/*.c src/cpu/*.c -lcunit

build:
	gcc -o computer src/memory/*.c src/registers/*.c src/cpu/*.c src/screen/*.c

clean: 
	rm testoutput
